{% set name = "ros-rostime" %}
{% set version = "0.6.13-1" %}
{% set sha256 = "0aedc8397fb212ed0e019f63d739508a0b009e1a22943a86f8e4be20769b5157" %}
{% set version = "0.6.13-1" %}
{% set sha256 = "0aedc8397fb212ed0e019f63d739508a0b009e1a22943a86f8e4be20769b5157" %}

package:
  name: {{ name }}
  version: {{ version.split("-")[0] }}

source:
  url: https://github.com/ros-gbp/roscpp_core-release/archive/release/melodic/rostime/{{ version }}.tar.gz
  sha256: {{ sha256 }}


build:
  number: 0  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - cmake
  host:
    - ros-conda-mutex * melodic
    - ros-conda-base
    - python
    - catkin_pkg
    - ros-cpp-common
    - boost-cpp
    - ros-catkin
  run:
    - ros-conda-mutex * melodic
    - ros-conda-base
    - ros-cpp-common
    - boost-cpp

test:
  requires:
    - rospkg
  commands:
    - export ROS_ROOT=$PREFIX && python -c "import rospkg;s = rospkg.RosPack();ret = s.get_path('rostime');print(ret)"

about:
  home: http://ros.org/wiki/rostime
  summary: |
    Time and Duration implementations for C++ libraries, including roscpp.
  description: |
    Time and Duration implementations for C++ libraries, including roscpp.
  license: BSD-3-Clause
  license_file: include/ros/duration.h

extra:
  recipe-maintainers:
    - wolfv
    - lesteve
    - seanyen
